name: Release

on:
  push:
    branches:
      - wolfgang/develop

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  
  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - id: version
        name: Make version
        run: |
          CURRENT_DATE=$(date "+%Y.%m.%d")
          NEW_VERSION=${CURRENT_DATE}-${GITHUB_RUN_NUMBER}
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
      - name: Set version
        run: |
          npm version "${{steps.version.outputs.version}}" --no-git-tag-version
      - name: Node CI
        run: npm ci
      - name: Package Extension
        run: npx @vscode/vsce package
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          path: sl-vscode-edit-*.vsix
          retention-days: 30
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{steps.version.outputs.version}}
          artifacts: sl-vscode-edit-*.vsix
      